# Supabase Configuration for GlobFam

project_id = "globfam"

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enable_signup = true
enable_anonymous_sign_ins = false
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[storage]
enabled = true

[storage.image_transformation]
enabled = true

[[storage.buckets]]
name = "documents"
public = false
file_size_limit = 52428800
allowed_mime_types = ["image/*", "application/pdf", "text/csv", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]

[[storage.buckets]]
name = "avatars"
public = true
file_size_limit = 5242880
allowed_mime_types = ["image/*"]

[local]
enabled = true