# Root nixpacks.toml for Railway deployment
# Simplified configuration for globfam-platform

[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
# Simple npm install commands without flags
cmds = [
  "cd globfam-platform && npm install",
  "cd globfam-platform/backend && npm install",
  "cd globfam-platform/frontend && npm install"
]

[phases.build]
cmds = [
  "cd globfam-platform/backend && npm run build",
  "cd globfam-platform/backend && npx prisma generate",
  "cd globfam-platform/frontend && npm run build"
]

[start]
cmd = "cd globfam-platform && npm run start:railway"

[variables]
NODE_ENV = "production"