# Ultra-simple nixpacks configuration for debugging
[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  "echo '=== Installing root dependencies ==='",
  "cd globfam-platform && npm install || (echo 'Root install failed' && exit 1)",
  "echo '=== Installing backend dependencies ==='",
  "cd globfam-platform/backend && npm install --no-scripts || (echo 'Backend install failed' && exit 1)",
  "echo '=== Installing frontend dependencies ==='",
  "cd globfam-platform/frontend && npm install || (echo 'Frontend install failed' && exit 1)"
]

[phases.build]
cmds = [
  "echo '=== Building backend ==='",
  "cd globfam-platform/backend && npx prisma generate && npm run build",
  "echo '=== Building frontend ==='",
  "cd globfam-platform/frontend && npm run build"
]

[start]
cmd = "cd globfam-platform && npm run start:railway"

[variables]
NODE_ENV = "production"