[phases.setup]
nixPkgs = ["nodejs-18_x", "libc6-compat"]
aptPkgs = []

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm config set registry https://registry.npmjs.org/",
  "npm ci --legacy-peer-deps --no-audit --no-fund --prefer-offline"
]
cacheDirectories = ["/app/node_modules", "/app/.next/cache"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=768"
NEXT_TELEMETRY_DISABLED = "1"