[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.build]
cmd = "rm -f package-lock.json && npm install --legacy-peer-deps && npx prisma generate && npx prisma migrate deploy && npm run build"

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"