[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.install]
cmds = ["npm ci --omit=dev --legacy-peer-deps || npm install --omit=dev --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "sh start-production.sh"

[variables]
NODE_ENV = "production"