[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npm run build"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3