version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: globfam-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: globfam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - globfam-network

  redis:
    image: redis:7-alpine
    container_name: globfam-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - globfam-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: globfam-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/globfam?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this
      JWT_REFRESH_SECRET: your-refresh-token-secret-change-this
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - globfam-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: globfam-frontend
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - globfam-network
    command: npm run dev

networks:
  globfam-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: